kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.services.db.port }}
      targetPort: {{ .Values.services.db.targetPort }}
