kind: Service
apiVersion: v1
metadata:
  name: {{ include "my-chart.fullname" . }}-ms10-demo1-service
spec:
  selector:
    app: {{ include "my-chart.fullname" . }}-ms10-demo1
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.services.ms10demo1.port }}
      targetPort: {{ .Values.services.ms10demo1.targetPort }}
