apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: {{ .Values.services.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{ .Values.services.db.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.services.db.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.services.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.services.db.password }}
          ports:
            - containerPort: {{ .Values.services.db.containerPort }}
