apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-mysql-deployment
spec:
  replicas: {{ .Values.services.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-chart.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "my-chart.fullname" . }}-db
    spec:
      containers:
        - name: {{ include "my-chart.fullname" . }}-db
          image: {{ .Values.services.db.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.services.db.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.services.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.services.db.password }}
          ports:
            - containerPort: {{ .Values.services.db.containerPort }}
