apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-ms10-demo1-deployment
spec:
  replicas: {{ .Values.services.ms10demo1.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-chart.fullname" . }}-ms10-demo1
  template:
    metadata:
      labels:
        app: {{ include "my-chart.fullname" . }}-ms10-demo1
    spec:
      containers:
      - name: {{ include "my-chart.fullname" . }}-ms10-demo1
        image: {{ .Values.services.ms10demo1.image }}
        ports:
          - containerPort: {{ .Values.services.ms10demo1.containerPort }}
